# -*- coding: utf-8 -*-
#

OBJECT_TYPE_READ_USER_INFO = 1
OBJECT_TYPE_PARAMETER = 2
OBJECT_TYPE_MESSAGE = 3
OBJECT_TYPE_CUSTOM_DATALOG = 5
OBJECT_TYPE_DATALOG_TX = 0x0101

PROPERTY_ID_READ = 0x01
PROPERTY_VALUE_QSP = 0x05
PROPERTY_MIN_QSP = 0x06
PROPERTY_MAX_QSP = 0x07
PROPERTY_LEVEL_QSP = 0x08               # To get access level: VIEW_ONLY, BASIC, EXPERT, etc.
PROPERTY_UNSAVED_VALUE_QSP = 0x0D
PROPERTY_LAST = 0xEE                    # Not Studer specific. Introduced by boozo